services:
  #web:
  #container_name: spotify
  #image: acpnext
  #build: .
  #ports:
  #  - 3000:3000
  #volumes:
  #  - ./spotify/clone/:/app

  back:
    container_name: boffice
    image: acpnext
    build: .
    ports:
      - 3001:3000
    volumes:
      - ./spotify/backoffice/:/app
