services:
  web:
    container_name: spotify
    image: acpnext
    build:
      context: .
      dockerfile: Dockerfile_users
    ports:
      - "3000:3000"
    volumes:
      - ./spotify/clone/:/app
      - /app/node_modules

  banco:
    image: postgres:18-alpine3.23
    container_name: banco
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./dados/:/var/lib/postgresql

  back:
    container_name: boffice
    image: acpnext
    build:
      context: .
      dockerfile: Dockerfile_adm
    ports:
      - "3001:3000"
    volumes:
      - ./spotify/backoffice/:/app
      - /app/node_modules
